### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by xavierhardy** [graylog-labs/cli-dashboard#24]
Hi,
I was trying to run the dashboard as I have seen most of the tickets I've opened are closed/going to be closed. I have installed node v5.9.1 (requirement is > v4.0.0), and I can't start the dashboard (not even `--help`).

```
./node/bin/graylog-dashboard --help
/home/xhardy/Programs/node/lib/node_modules/graylog-cli-dashboard/graylog-dashboard.js:46
    const {argv} = yargs;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by xavierhardy** [comment]
It works with the LTS version (v6.9.1). Using package version 1.0.0 .

**Comment by KDGundermann** [comment]
the same problem here running on Ubuntu:
```
klaus@rails64-dev:~$ npm version
{ npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.6',
  openssl: '1.0.2g-fips',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
  klaus@rails64-dev:~$ uname -a
  Linux rails64-dev 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64   GNU/Linux
```

**Comment by STRML** [comment]
See the above comment @KDGundermann; your node version is out of date.

**Comment by xavierhardy** [comment]
Change the requirement to node > v6.0.0, please.

**Comment by STRML** [comment]
I did days ago - please check the project before commenting.
