### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Neocid** [graylog-labs/cli-dashboard#27]
Node version: v7.4.0
Npm version: 4.0.5

When I try to pull our graylog server, I get an error. 

The web interface is available at this url: https://server.example.com/streams/#streamID#/

When I try to use the graylog-dashboard, I get this error:

graylog-dashboard --server-url https://server.example.com --stream-title #streamID#
`
TypeError: Cannot read property 'id' of undefined
    at storeStreams (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/graylog-dashboard.js:106:31)
    at PassThroughHandlerContext.finallyHandler (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:567:18)
    ar Promise._settlePromise0 (/PathToNodeLibrary/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:612:10)`

Any idea what I am doing wrong?

**Comment by andho** [comment]
You have to specify the stream title, not the stream id.
