### ISSUE TITLE
Bad status code: 404 Not Found {"type":"ApiError","message":"HTTP 404 Not Found"}

### ISSUE THREAD

**Issue by nizzan** [graylog-labs/cli-dashboard#35]
Does this support Graylog 3.2+?

I'm trying to run this from the CLI on a Ubuntu 18.04.
But i keep getting an error when launching it.
I'm on graylog version 3.0.2+1686930, codename Space Moose

My startup is: 
```graylog-dashboard -g --api-host 127.0.0.1:9000 --api-protocol http --stream-title "All messages" --username ***** --password *****```

And the error message i keep getting is:
```
Error: Could not get Graylog version. Bad status code: 404 Not Found {"type":"ApiError","message":"HTTP 404 Not Found"}
    at makeRequest.then.catch (/usr/local/lib/node_modules/graylog-cli-dashboard/lib/graylog-api.js:111:13)
    at tryCatcher (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/graylog-cli-dashboard/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Any ideas? :)

**Comment by jjo93sa** [comment]
Have you tried removing the :9000 from your --api-host parameter? 9000 is the default, so I don't think it is needed.

This is how I can get it to connect to my graylog 3.1.2 server (I just specify the IP address no port). However, so far I've only managed to get the graphs updating. The list of messages does not update, and seems to stay fixed with the first few in the stream.
